---

plugins:
  - import
  - jest

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/prefer-default-export: 0
  linebreak-style: 0